apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  annotations:
    cnrm.cloud.google.com/allow-stopping-for-update: "true"
    cnrm.cloud.google.com/project-id: lasse-dvt-kcc-ba3k
  name: vm-from-yaml
  labels:
    created-from: "image"
    network-type: "subnetwork"
spec:
  machineType: n1-standard-1
  zone: europe-west4-a
  bootDisk:
    initializeParams:
      size: 24
      type: pd-ssd
      sourceImageRef:
        external: debian-cloud/debian-11
  networkInterface:
    - subnetworkRef:
        external: projects/lasse-dvt-kcc-ba3k/regions/europe-west4/subnetworks/primary-subnet
      accessConfig:
        - networkTier: premium
          natIpRef:
              name: ip-vm-from-yaml
  tags:
    - http-server
  metadataStartupScript: |-
    #!/bin/bash
    apt update
    apt install -y nginx
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: ip-vm-from-yaml
  annotations:
    cnrm.cloud.google.com/project-id: lasse-dvt-kcc-ba3k
spec:
  location: europe-west4

#  minCpuPlatform: "Intel Skylake"
#  serviceAccount:
##    serviceAccountRef:
 ##     name: inst-dep-cloudmachine
#    scopes:
#    - compute-rw
#    - logging-write
